CREATE TABLE keys(
    UserId UNIQUE INT,
     PublicKey  UNIQUE VARCHAR(255)
);

CREATE TABLE user(
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP
);

CREATE TABLE chats(
    id VARCHAR(255)  NOT NULL PRIMARY KEY, 
    admin_user_id VARCHAR(255) NOT NULL,
    chat_status VARCHAR(50) DEFAULT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

);